spring:
  application:
    name: wardrobe-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/wardrobe
          jwk-set-uri: http://localhost:8081/realms/wardrobe/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: wardrobe-pwa
      principal-attribute: preferred_username
logging:
  level:
    org.springframework.security: DEBUG